### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by bkuhls** [notspiff/screensaver.cpblobs#1]
Hi, is it possible to add license information to the package?

**Comment by notspiff** [comment]
this one specifically mentions xbmc in its code so i have assigned GPL2 to everything.

note that the screensaver is not currently working.

**Comment by notspiff** [comment]
@bkuhls the screensaver is now in working order. i rebased the master branch (naughty me); this was never supposed to be used by anybody. of course that is the last time that happens now that i consider it public.
